# Generated by Django 2.0.2 on 2018-05-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='e-mail')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'pessoas',
                'verbose_name': 'pessoa',
            },
        ),
    ]
