# Generated by Django 2.0.2 on 2018-05-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Gaget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50, verbose_name='Instrumento')),
                ('Modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('Fabricante', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('Status', models.CharField(max_length=50, verbose_name='Status')),
                ('Torre', models.CharField(max_length=50, verbose_name='Torre')),
                ('Slope', models.FloatField(verbose_name='slope')),
                ('Offset', models.FloatField(verbose_name='off-set')),
                ('Serial', models.CharField(max_length=50, verbose_name='Serial #')),
                ('Calibracao', models.CharField(max_length=50, verbose_name='Calibração #')),
                ('doc_Calibracao', models.FileField(upload_to='documents/')),
                ('Data_inicial', models.DateTimeField(auto_now_add=True, verbose_name='Data instalação')),
                ('Data_final', models.DateTimeField(auto_now_add=True, verbose_name='Data desinstalação')),
                ('Obs', models.TextField(verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'pessoa',
                'ordering': ['Tipo'],
                'verbose_name_plural': 'pessoas',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
