# Generated by Django 2.0.2 on 2018-05-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0002_auto_20180503_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_gaget',
            options={'ordering': ['Tipo']},
        ),
    ]
