# Generated by Django 2.0.2 on 2018-05-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0003_auto_20180503_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_gaget',
            name='id_ggt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
