# Generated by Django 2.0.2 on 2018-05-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0005_remove_tb_gaget_id_ggt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_gaget',
            options={},
        ),
        migrations.AlterField(
            model_name='tb_gaget',
            name='doc_Calibracao',
            field=models.FileField(upload_to='static/documents/'),
        ),
    ]
